# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Oasis_Login' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'
  pod 'Then'

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
   #Pods for Oasis_Login

end
